export const EVENT_RENDER_BATTLE_AND_PLAYERS = 'EVENT_START_BATTLE';
export const EVENT_RENDER_PLAYER_LEFT = 'EVENT_RENDER_PLAYER_LEFT';
export const EVENT_RENDER_PLAYER_UP = 'EVENT_RENDER_PLAYER_UP';
export const EVENT_RENDER_PLAYER_RIGHT = 'EVENT_RENDER_PLAYER_RIGHT';
export const EVENT_RENDER_PLAYER_DOWN = 'EVENT_RENDER_PLAYER_DOWN';
export const EVENT_RENDER_BATTLE = 'EVENT_RENDER_BATTLE';
export const EVENT_CELL_VIEW_PUT = 'EVENT_UPDATE_BATTLE';

export const EVENT_CELL_VIEW_MOVE = 'EVENT_CELL_MOVE';
export const EVENT_CELL_VIEW_OUT = 'EVENT_CELL_OUT';

export const EVENT_SERVER_START = 'EVENT_SERVER_START';
export const EVENT_SERVER_SEND_START = 'EVENT_SERVER_SEND_START'

export const EVENT_PEER_START = 'EVENT_CLIENT_START';
export const EVENT_PEER_SILENT_START = 'EVENT_PEER_SILENT_START';
export const EVENT_PEER_SEND_PUT = 'EVENT_PEER_SEND_PUT';

// export const

