export const EVENT_RENDER_BATTLE_AND_PLAYERS = 'EVENT_START_BATTLE';
export const EVENT_CELL_VIEW_PUT = 'EVENT_UPDATE_BATTLE';

export const EVENT_CELL_VIEW_MOVE = 'EVENT_CELL_MOVE';
export const EVENT_CELL_VIEW_OUT = 'EVENT_CELL_OUT';

export const EVENT_ROOM_START = 'EVENT_ROOM_START';
export const EVENT_ROOM_SEND_START = 'EVENT_ROOM_SEND_START'

export const EVENT_PEER_START = 'EVENT_CLIENT_START';
export const EVENT_PEER_SEND_PUT = 'EVENT_PEER_SEND_PUT';
